img_size: 512
down_stride: 4

gpu: 0
class_name: ['face']
model_name: 'resnet18'
save_model: 'resnet18.pth'
save_path: 'save_model'

Loss: # hyperparameters for loss function
  alpha: 1.
  beta: 0.1
  gamma: 1.

CNN:
  heads: {'hm':1, 'wh':2, 'reg':2}
  head_conv: 64
  pretrained: True
  pretrained_path: 'pretrained_model'
  pretrained_model: 'ctdet_pascal_resdcn18_512.pth'

Optimizer: # hyperparameters for optimize alogorithms
  lr: 1.25e-4
  gamma: 0.1
  weight_decay: 1.0e-6
  milestones: [15, 25, 30]
  epochs: 35

expand_percent: 0.05
score_th: 0.1
train_batch: 32
valid_batch: 64

train_path: 'dataset/wider_face/WIDER_train'
valid_path: 'dataset/wider_face/WIDER_val'
test_path: 'images'
save_img_path: 'result'